/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wuja6_entrance_CannyTestMain */

#ifndef _Included_com_wuja6_android_getimageedgeapp_task_OpenCVProcessTask
#define _Included_com_wuja6_android_getimageedgeapp_task_OpenCVProcessTask
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     com_wuja6_entrance_CannyTestMain
* Method:    getEdgeByCanny
* Signature: (Ljava/lang/String;Ljava/lang/String;DDI)Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_com_wuja6_android_getimageedgeapp_task_OpenCVProcessTask_getEdgeByCanny
        (JNIEnv *, jobject, jstring, jstring, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
